WIP: Background export
alephdata/aleph pull request #1282
Opened 2020-07-22 07:20 UTC by sunu

refs #959

2020-08-27 16:24 UTC, pudo requested changes
This looks amazing, overall! Let me suggest some points:

* I think we ought to emit signed export URLs (like with `archive_url`, especially in the email. Lets have a helper function, `export_url` in logic.util.

* I think "PUBLISH_EXPORT" is a misnomer, given that we'll want to implement actual publication at some stage later. Maybe "COMPLETE_EXPORT"?

* The ROLE_PREFIX thing: would it be nicer to make both prefixed: collections and roles? This way SL 'datasets' clearly can be both. 

* I think `convertUTCDateToLocalDate` wants to live in a util helper file :) Should we use it for notifications or is that somehow not an issue there?

* Kudos on the ref-counting in should_delete :) 

* Can you merge the migrations (just turn into one file and use the max() and min() hashes) and get rid of the `downgrade()` contents? 

Really impressive work.

2020-09-02 07:43 UTC, sunu commented
ingestors tests keep breaking in the CI for some reason. I don't know why yet.

2020-09-02 07:58 UTC, pudo commented
That's setuptools, I suspect

2020-09-07 14:40 UTC, pudo approved these changes

2020-09-07 14:40 UTC, merged